QuanLyThuVien/QuanLyThuVien/Areas/Admin/Controllers/AudioBookController.cs
using BusinessLogic.ViewModel;
using DataProvider.Model;
using QuanLyThuVien.Service;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace QuanLyThuVien.Areas.Admin.Controllers
{
    public class AudioBookController : BaseController
    {
        private IAudioBookService _audioBookService;
        private IBookService _bookService;

        public AudioBookController(IAudioBookService audioBookService, IBookService bookService)
        {
            this._audioBookService = audioBookService;
            this._bookService = bookService;
        }

        public ActionResult Index()
        {
            var audioList = _audioBookService.GetAllAudioBookView_Service();
            return View("Index", audioList);
        }

        [HttpPost]
        public ActionResult UploadAudio1(AudioBookModelView model)
        {
            string fileName = null;
            int fileSize = 0;
            int Size = 0;

            if(model.File != null)
            {
                fileName = Path.GetFileName(model.File.FileName);
                fileSize = model.File.ContentLength;
                Size = fileSize / 1000000;
                model.File.SaveAs(Server.MapPath("~/AudioFile/" + fileName));

                AudioBook audio = new AudioBook
                {
                    BookID = model.BookID,
                    AudioID = model.AudioID,
                    AudioName = model.AudioName,
                    FileAudioSize = Size,
                    FileAudioPath = "~/AudioFile/" + fileName,
                    Alias = model.Alias
                };

                _audioBookService.Update(audio);

                return RedirectToAction("Index");
            }
            else
            {
                AudioBook audio = _audioBookService.GetAudioBookByBookIDAndAudioID(model.BookID, model.AudioID);
                audio.AudioName = model.AudioName;
                audio.Alias = model.Alias;
                _audioBookService.Update(audio);

                return RedirectToAction("Index");
            }                                
        }

        [HttpPost]
        public ActionResult UploadAudio2(AudioBookModelView model)
        {
            string fileName = Path.GetFileName(model.File.FileName);
            int fileSize = model.File.ContentLength;
            int Size = fileSize / 1000000;
            model.File.SaveAs(Server.MapPath("~/AudioFile/" + fileName));
            AudioBook audio = new AudioBook
            {
                BookID = model.BookID,
                AudioID = model.AudioID,
                AudioName = model.AudioName,
                FileAudioSize = Size,
                FileAudioPath = "~/AudioFile/" + fileName,
                Alias = model.Alias
            };
            _audioBookService.Create(audio);
            return RedirectToAction("Index");
        }

        public ActionResult GetListNameBook()
        {
            var listBook = _bookService.GetAll().Select(x => new
            {
                idBook = x.BookID,
                nameBook = x.BookName
            });

            return Json(listBook, JsonRequestBehavior.AllowGet);
        }

        //Update audio
        public ActionResult GetAudiobyID(int idBook, int idAudioBook)
        {
            AudioBook audio = _audioBookService.GetAudioBookByID_Service(idBook, idAudioBook);
            return Json(new
            {
                BookID = audio.BookID,
                AudioID = audio.AudioID,
                AudioName = audio.AudioName,
                Alias = audio.Alias,
                UrlSave = audio.FileAudioPath
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteAudio(int idBook, int idAudioBook)
        {
            AudioBook audio = _audioBookService.GetAudioBookByID_Service(idBook, idAudioBook);
            _audioBookService.Delete(audio);
            //_audioBookService.Save();
            System.IO.File.Delete(Server.MapPath(audio.FileAudioPath));
            return RedirectToAction("Index");
        }
    }
}

QuanLyThuVien/QuanLyThuVien/Controllers/BookController.cs
using BusinessLogic.Repository;
using BusinessLogic.Repository.Base;
using QuanLyThuVien.Models;
using QuanLyThuVien.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThuVien.Controllers
{
    public class BookController : Controller
    {
        private IBookService _bookService;
        private IBookCategoryService _bookCategoryService;
        private IAuthorService _authorService;
        private IEbookService _ebookService;
        private IUserService _userService;
        private ITypeEbookService _typeEbookService;
        private IAudioBookService _audioBookService;
        private IChapterDetailService _chapterDetailService;
        private IInformationService _informationService;

        public BookController(IInformationService informationService, IChapterDetailService chapterDetailService , IAudioBookService audioBookService, ITypeEbookService typeEbookService, IUserService userService, IAuthorService authorService, IBookCategoryService bookCategoryService, IBookService bookService, IEbookService ebookService)
        {
            this._authorService = authorService;
            this._informationService = informationService;
            this._chapterDetailService = chapterDetailService;
            this._audioBookService = audioBookService;
            this._bookCategoryService = bookCategoryService;
            this._bookService = bookService;
            this._ebookService = ebookService;
            this._userService = userService;
            this._typeEbookService = typeEbookService;
        }

        public BookController()
        {

        }

        //Trang chủ
        public ActionResult Index()
        {
            return View();
        }

        //Lấy tất cả sách in ra trên trang chủ
        [ChildActionOnly]
        public ActionResult BodyListBook(/*int page = 1, int pageSize = 10*/)
        {
            //var Execute = new BookRepository();
            //var modelBook = Execute.GetAll();

            var modelBook = _bookService.GetAll();

            //var modelBook = Execute.ListAllWithPageListBook(page, pageSize);
            return PartialView(modelBook);
        }

        //Lấy ra bảng bên phải
        [ChildActionOnly]
        public ActionResult TaoBangBenPhai()
        {
            var model = _bookCategoryService.GetAll();
            return PartialView(model);
        }

        //Cấu hình trong RouteConfig
        //Controller thực hiện khi người dùng click chọn thể loại sách trên combobox hoặc trên bảng slide bên phải
        public ActionResult Category(string SeoTitle, int page = 1, int pageSize = 20)
        {
            if (SeoTitle == "tat-ca-sach")
            {
                //var allBook = new BookRepository().GetAll();
                var allBook = _bookService.ListAllWithPageListBook(page, pageSize);
                var TheLoaiSachDuocChon = _bookCategoryService.GetByString(SeoTitle);
                ViewBag.TheLoaiSach = _bookCategoryService.GetById(TheLoaiSachDuocChon.CategoryID);
                return View(allBook);
            }
            else
            {
                var TheLoaiSachDuocChon = _bookCategoryService.GetByString(SeoTitle);
                //var BookTrongTheLoaiSachDuocChon = new BookRepository().ListBookByCategory(TheLoaiSachDuocChon.CategoryID);
                var BookTrongTheLoaiSachDuocChon = _bookService.ListBookByCategoryWithPageListBook(TheLoaiSachDuocChon.CategoryID, page, pageSize);
                ViewBag.TheLoaiSach = _bookCategoryService.GetById(TheLoaiSachDuocChon.CategoryID);
                return View(BookTrongTheLoaiSachDuocChon);
            }
            //return View();
        }

        public JsonResult ListName(string q)
        {
            var data = _bookService.ListName(q);
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        //Cấu hình trong RouteConfig
        //Controller thực hiện khi người dùng click chọn thông tin cụ thể trên combobox Thông tin 
        //
        public ActionResult Information(string MetaTitle)
        {
            var ThongTinDuocChon = _informationService.GetByString(MetaTitle);
            return View(ThongTinDuocChon);
        }

        //Cấu hình trong RouteConfig
        //Controller thực hiện khi click vào một cuốn sách bất kỳ
        //Chi tiết cuốn sách được Click
        public ActionResult ShowBook(int bookID)
        {
            var Book = _bookService.GetById(bookID);
            ViewBag.Author = _authorService.GetById(Book.AuthorID.Value);
            ViewBag.Category = _bookCategoryService.GetById(Book.CategoryID.Value);
            ViewBag.Ebook = _ebookService.GetAllListEbookViewByID(bookID);
            //ViewBag.Chapter = new ChapterDetailRepository().GetById(bookID);
            return View(Book);
        }

        //Button Search
        public ActionResult Search(string keyword, int page = 1, int pageSize = 2)
        {
            //var TheLoaiSachDuocChon = new BookCategoryRepository().GetByString(SeoTitle);
            ////var BookTrongTheLoaiSachDuocChon = new BookRepository().ListBookByCategory(TheLoaiSachDuocChon.CategoryID);
            var BookSearch = _bookService.SearchBook(keyword, page, pageSize);
            ViewBag.Keyword = keyword;
            // ViewBag.TheLoaiSach = new BookCategoryRepository().GetById(TheLoaiSachDuocChon.CategoryID);
            return View(BookSearch);
        }

        public ActionResult BodyListBook(int page = 1, int pageSize = 20)
        {
            //var Execute = new BookCategoryRepository();
            var Execute = _bookService;
            //var model = Execute.GetAll();
            var model = Execute.ListAllWithPageListBook(page, pageSize);
            //Lấy model đẩy xuống View
            return PartialView("BodyListBook", model);
        }

        [ChildActionOnly]
        public ActionResult ComboboxDanhSachChuong(string chapAlias)
        {
            var ChuongSachDuocChon = _chapterDetailService.GetByString(chapAlias);
            //var Book = new BookRepository().ListChapterDetailOfBook(ChuongSachDuocChon.IDBook);
            var modelListAllChuongCuaSach = _bookService.ListChapterDetailOfBook(ChuongSachDuocChon.IDBook);
            return PartialView(modelListAllChuongCuaSach);
        }

        [ChildActionOnly]
        public ActionResult DanhSachChuong(int bookID)
        {
            var Book = _bookService.GetById(bookID);
            var model = _bookService.ListChapterDetailOfBook(Book.BookID);
            return PartialView(model);

        }


        //Khi người dùng click vào button Audio Book
        [ChildActionOnly]
        public ActionResult ButtonAudioBook(int bookID)
        {
            var Book =  _bookService.GetById(bookID);
            ViewBag.Book = Book.Alias;
            var model = _audioBookService.ListAudioByBook(Book.BookID);
            return PartialView(model);
        }

        //Load nút Button ReadOnline
        [ChildActionOnly]
        public ActionResult ButtonReadOnline(int bookID)
        {
            var Book = _bookService.GetById(bookID);
            var model = _bookService.TheFirstChapOfBook(Book.BookID);
            return PartialView(model);
        }



        //Cấu hình trong RouteConfig
        //Controller thực hiện việc đọc online (sau khi click vào button Đọc Online)
        public ActionResult ReadOnline(string chapAlias)
        {
            var ChuongSachDuocChon = _chapterDetailService.GetByString(chapAlias);
            ViewBag.Book = _bookService.GetById(ChuongSachDuocChon.IDBook);
            ViewBag.ChuongSachDuocChon = ChuongSachDuocChon;
            var ListAllChuongTruChuongDauTien = _bookService.ListChapterDetailOfBookDeleteFirst(ChuongSachDuocChon.IDBook);
            return View(ListAllChuongTruChuongDauTien);
        }

        //Khi click vào Button Audio
        public ActionResult ShowAudioBook(string audioName)
        {
            //var AudioBook = new AudioBookRepository().ListAllAudioBook();
            var AudioBook = _audioBookService.ListAudioByNameAudio(audioName);
            var Book = _bookService.GetById(AudioBook.BookID);
            ViewBag.Book = Book;
            ViewBag.Author = _authorService.GetById(Book.AuthorID.Value);
            ViewBag.Category = _bookCategoryService.GetById(Book.CategoryID.Value);
            return View(AudioBook);
        }

        public ActionResult ChangeChapter(string chapAlias)
        {
            var ChuongSachDuocChon = _chapterDetailService.GetByString(chapAlias);
            ViewBag.Book = _bookService.GetById(ChuongSachDuocChon.IDBook);
            ViewBag.ChuongSachDuocChon = ChuongSachDuocChon;
            var ListAllChuongTruChuongDuocChon = _bookService.ListChuongSachTruChuongDuocChon(ChuongSachDuocChon.IDBook, ChuongSachDuocChon.ChapterID);
            return View(ListAllChuongTruChuongDuocChon);
        }
    }
}

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/AudioBook/Audio.cshtml
@model DataProvider.Model.AudioBook

@{
    ViewBag.Title = "Audio";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}

<h2>Audio</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AudioBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookID, "BookID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AudioID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AudioID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AudioID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AudioName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AudioName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AudioName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileAudioSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileAudioSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileAudioSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileAudioPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileAudioPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileAudioPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/AudioBook/UploadAudio.cshtml
@{
    ViewBag.Title = "UploadAudio";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}

@section scripts
{
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="/Content/bootstrap.min.css" rel="stylesheet" />
        <script src="/scripts/jquery-3.3.1.min.js"></script>
        <script src="/scripts/bootstrap.min.js"></script>*@

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();

            $("audio").on("play", function () {
                $("audio").not(this).each(function (index, audio) {
                    audio.pause();
                });

            });
        });
    </script>
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Audio List</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <!--Button Thêm Mới-->
                        <button style="margin-left: 27px;margin-bottom:10px;" type="button" class="btn btn-primary rounded-0" data-toggle="modal" data-target="#myModal">
                            <i class="fa fa-plus-circle"></i> Thêm Audio
                        </button>


                        <div class="modal fade" id="myModal">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Upload New Audio File</h4>
                                        <button type="button" class="close" data-dismiss="modal">×</button>
                                    </div>

                                    <!--Form chọn ảnh và upload-->
                                    <div class="modal-body">
                                        @using (Html.BeginForm("UploadAudio", "AudioBook", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                        {
                                            
                                            @*<!---->
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.BookID, "BookID", htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.DropDownList("BookID", null, htmlAttributes: new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.BookID, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.AudioID, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.AudioID, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.AudioID, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.AudioName, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.AudioName, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.AudioName, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.FileAudioSize, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.FileAudioSize, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.FileAudioSize, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.FileAudioPath, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.FileAudioPath, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.FileAudioPath, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Create" class="btn btn-default" />
                                                </div>
                                            </div>
                                            <!---->*@
                                            <div class="form-group">
                                                <label>Choose File:</label>
                                                <div class="input-group">
                                                    <div class="custom-file">
                                                        <input type="file" id="fileupload" name="fileupload" class="custom-file-input" />
                                                        <label class="custom-file-label"></label>
                                                    </div>
                                                    <div class="input-group-append">
                                                        <input type="submit" id="btnUpload" class="btn btn-secondary" value="Upload" />
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                    <table id="dataTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>BookID</th>
                                <th>AudioID</th>
                                <th>Audio Name</th>
                                <th style="width:90px;">File Size(MB)</th>
                                <th>Alias</th>
                                <th>Play Audio</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td>@item.BookID</td>
                                    <td>@item.AudioID</td>
                                    <td>@item.AudioName</td>
                                    <td>@item.FileAudioSize</td>
                                    <td>@item.Alias</td>
                                    <td>
                                        <audio controls>
                                            <source src="@Url.Content(@item.FileAudioPath)" type="audio/ogg">
                                        </audio>
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


<!--Body-->
@*<div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Audio Book Record</h3>
                    </div>
                    <div class="box-body">
                        <div class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6">
                                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("UploadAudio","Book")'">Add New Audio Book</button>
                                </div>
                                <div class="col-sm-6" style="text-align:right">
                                    <label>Search: <input type="text" class="form-control" id="inputKeyword" /></label>
                                    <button class="btn" onclick="SearchClick()">Tìm</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <br />
                                    <table id="#mytab" class="table table-hover dataTable table-bordered">
                                        <thead>
                                            <tr role="row">
                                                <th>BookID</th>
                                                <th>AudioID</th>
                                                <th>Audio Name</th>
                                                <th>File Audio Size(MB)</th>
                                                <th>Alias</th>
                                                <th>Play Audio</th>
                                            </tr>
                                        </thead>
                                        <tbody class="tbody">

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row" style="text-align: right">
                                <div class="dataTables_paginate paging_simple_numbers" style="padding-right: 15px">
                                    <ul class="pagination" id="phantrang" style="margin-top: -10px;margin-bottom: 0px;"></ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@