QuanLyThuVien/QuanLyThuVien/Areas/Admin/Controllers/ChapterDetailController.cs
using BusinessLogic.Repository;
using DataProvider.Model;
using QuanLyThuVien.Areas.Admin.Models;
using QuanLyThuVien.Models;
using QuanLyThuVien.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThuVien.Areas.Admin.Controllers
{
    public class ChapterDetailController : BaseController
    {
        private IBookService _bookService;
        private IBookCategoryService _bookCategoryService;
        private IAuthorService _authorService;
        private IEbookService _ebookService;
        private IUserService _userService;
        private ITypeEbookService _typeEbookService;
        private IChapterDetailRepository _chapterDetailRepository;

        public ChapterDetailController(IChapterDetailRepository chapterDetailRepository, ITypeEbookService typeEbookService, IUserService userService, IAuthorService authorService, IBookCategoryService bookCategoryService, IBookService bookService, IEbookService ebookService)
        {
            this._authorService = authorService;
            this._chapterDetailRepository = chapterDetailRepository;
            this._bookCategoryService = bookCategoryService;
            this._bookService = bookService;
            this._ebookService = ebookService;
            this._userService = userService;
            this._typeEbookService = typeEbookService;
        }
     
        // GET: Admin/ChapterDetail
        //ChapterDetailRepository chapterRepo = new ChapterDetailRepository();

        public ActionResult Index(int id = 0, string namebook = "")
        {
            return View();
        }

        public JsonResult List(int page = 1, string searchKey = "")
        {
            var result = _chapterDetailRepository.GetAllWithPageListSearch(page, 12, searchKey);
            return Json(new
            {
                data = result.Select(x => new {
                    IDBook = x.IDBook,NameBook=x.NameBook,
                    ChapterID = x.ChapterID,
                    Alias = x.Alias,
                    NameChapter = x.NameChapter,
                    Content = x.Content
                }),
                pageNumber = result.PageCount,
                keyword = searchKey
            }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetListBook()
        {
            var listbook = _bookService.GetAll().Select(x => new
            {
                BookID = x.BookID,
                BookName = x.BookName
            });
            return Json(listbook, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Add(int idbook)
        {
            LoadData(idbook);
            return View("Add");
        }


        public void LoadData(int idbook)
        {
            var book = _bookService.GetById(idbook);
            var lastChapter = _bookService.GetAllChapterByIDBook(1, 10000, idbook).Count;
            ViewBag.IDBookM = idbook;
            ViewBag.ChapterIDM = lastChapter;
            ViewBag.NameBook = book.BookName;
        }


        [HttpPost]
        public ActionResult Add(ChapterDetailModelInput chapter)
        {
            if (ModelState.IsValid)
            {
                if (_chapterDetailRepository.IsContainInListChapterBook(chapter.IDBook, chapter.ChapterID))
                {
                    ModelState.AddModelError("", "ChapterID này đã tồn tại");
                }
                else
                {
                    ChapterDetail ch = new ChapterDetail
                    {
                        IDBook = chapter.IDBook,
                        ChapterID = chapter.ChapterID,
                        Alias = chapter.Alias,
                        NameChapter = chapter.NameChapter,
                        Content = chapter.Content
                    };
                    _chapterDetailRepository.Create(ch);
                    return RedirectToAction("Edit", "Book", new { id = chapter.IDBook });
                }

            }
            LoadData(chapter.IDBook);
            return View();
        }


        [HttpPost]
        public JsonResult Delete(int bookid, int chapterid)
        {
            try
            {
                var chapter = _chapterDetailRepository.getByID2(bookid, chapterid);
                _chapterDetailRepository.Delete(chapter);
                return Json(new { success = true, message = "Xoá thành công" ,idbook=bookid}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult Search(string searchkey)
        {
            var data = _bookService.GetAllWithPageListSearch(1, 12, searchkey);
            return Json(new
            {
                data = data.Select(x => new
                {
                    BookID = x.BookID,
                    BookName = x.BookName,
                })
            }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult Edit(int idbook, int idChapter)
        {
            LoadData(idbook);
            var chapter = _chapterDetailRepository.getByID2(idbook, idChapter);
            var model = new ChapterDetailModelInput
            {
                IDBook = chapter.IDBook,
                ChapterID = chapter.ChapterID,
                Alias = chapter.Alias,
                NameChapter = chapter.NameChapter,
                Content = chapter.Content
            };
            return View("Edit", model);
        }


        [HttpPost]
        public ActionResult Edit(ChapterDetailModelInput chapter)
        {
            if (ModelState.IsValid)
            {
                ChapterDetail ch = new ChapterDetail
                {
                    IDBook = chapter.IDBook,
                    ChapterID = chapter.ChapterID,
                    Alias = chapter.Alias,
                    NameChapter = chapter.NameChapter,
                    Content = chapter.Content
                };
                _chapterDetailRepository.Update(ch);
                return RedirectToAction("Edit", "Book", new { id = chapter.IDBook });

            }
            LoadData(chapter.IDBook);
            return View();
        }


    }
}

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/ChapterDetail/Add.cshtml
@model QuanLyThuVien.Areas.Admin.Models.ChapterDetailModelInput

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}
@section headercss{

    <link href="/Content/jquery-ui.min.css" rel="stylesheet" />
}

@section scripts{

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="js/captcha/jquery.clientsidecaptcha.js" type="text/javascript"></script>
    <script src="/scripts/jquery-ui.min.js"></script>
    <script src="/Areas/Admin/Scripts/timkiem.js"></script>
    <script>

        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })

        var editor = CKEDITOR.replace('textareaContent', {
            customConfig: '/Content/admin2/plugins/ckeditor/config.js'
        })
    </script>
}


<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">New chapter</h3>
                </div>
                <div class="box-body">
                    <div>
                        <label>Tên sách: @ViewBag.NameBook</label> <br />
                        <label>ID: @ViewBag.IDBookM</label><br />
                        <label>Chapter mới nhất: @ViewBag.ChapterIDM</label>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.IDBook, "IDBook", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.IDBook, new { @class = "form-control", @Value = ViewBag.IDBookM, @disabled = "disabled" })
                                    @Html.HiddenFor(model => model.IDBook, new { @Value = ViewBag.IDBookM })
                                    @Html.ValidationMessageFor(model => model.IDBook, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ChapterID, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.ChapterID, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ChapterID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NameChapter, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NameChapter, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NameChapter, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @id = "textareaContent", @rows = "10" }, @id = "textareaContent" })
                                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Submit" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>

            </div>

        </div>
    </div>
    <div class="row" style="text-align: right">
        <div class="dataTables_paginate paging_simple_numbers" style="padding-right: 15px">
            <ul class="pagination" id="phantrang" style="margin-top: -10px;margin-bottom: 0px;"></ul>
        </div>
    </div>
</div>

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/ChapterDetail/Edit.cshtml
@model QuanLyThuVien.Areas.Admin.Models.ChapterDetailModelInput

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}
@section headercss{

    <link href="/Content/jquery-ui.min.css" rel="stylesheet" />
}

@section scripts{

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="js/captcha/jquery.clientsidecaptcha.js" type="text/javascript"></script>
    <script src="/scripts/jquery-ui.min.js"></script>
    <script src="/Areas/Admin/Scripts/timkiem.js"></script>
    <script>

        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })

        var editor = CKEDITOR.replace('textareaContent', {
            customConfig: '/Content/admin2/plugins/ckeditor/config.js'
        })
    </script>
}


<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Chương sách</h3>
                </div>
                <div class="box-body">
                    <div>
                        <label>Tên sách: @ViewBag.NameBook</label> <br />
                        <label>ID: @ViewBag.IDBookM</label><br />
                        <label>Chapter mới nhất: @ViewBag.ChapterIDM</label>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.IDBook, "IDBook", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.IDBook, new { @class = "form-control", @Value = ViewBag.IDBookM, @disabled = "disabled" })
                                    @Html.HiddenFor(model => model.IDBook)
                                    @Html.ValidationMessageFor(model => model.IDBook, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ChapterID, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.ChapterID, new { @class = "form-control", @disabled = "disabled" })
                                    @Html.HiddenFor(model => model.ChapterID)
                                    @Html.ValidationMessageFor(model => model.ChapterID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NameChapter, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NameChapter, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NameChapter, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @id = "textareaContent", @rows = "10" }, @id = "textareaContent" })
                                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Submit" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>

            </div>

        </div>
    </div>
    <div class="row" style="text-align: right">
        <div class="dataTables_paginate paging_simple_numbers" style="padding-right: 15px">
            <ul class="pagination" id="phantrang" style="margin-top: -10px;margin-bottom: 0px;"></ul>
        </div>
    </div>
</div>

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/ChapterDetail/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}
@section headercss{

}
@section scripts{
    <script src="~/Content/admin2/plugins/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Areas/Admin/Scripts/notify.min.js"></script>
    <script src="~/Areas/Admin/Scripts/ChapterDetail.js"></script>
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Danh sách chương sách</h3>
                    </div>
                    <div class="box-body">
                        <div class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                @*<div class="col-sm-6">
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="location.href='@Url.Action("Add","ChapterDetail")'">Thêm mới</button>
                                </div>*@
                                <div class="col-sm-6" style="text-align:right; margin-left: 533px;">
                                    <label>Search: <input type="text" class="form-control" id="inputKeyword" /></label>
                                    <button class="btn" onclick="SearchClick()">Tìm</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <br />
                                    <table id="#mytab" class="table table-hover dataTable table-bordered">
                                        <thead>
                                            <tr role="row">
                                                <th>
                                                    Tên sách
                                                </th>
                                                <th>
                                                    Chapter ID
                                                </th>
                                                <th>
                                                    Alias
                                                </th>
                                                <th>
                                                    Tên chapter
                                                </th>
                                                <th>
                                                    Nội dung
                                                </th>
                                                <th width="150px">
                                                    Action
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody class="tbody"></tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row" style="text-align: right">
                                <div class="dataTables_paginate paging_simple_numbers" style="padding-right: 15px">
                                    <ul class="pagination" id="phantrang" style="margin-top: -10px;margin-bottom: 0px;"></ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>