QuanLyThuVien/QuanLyThuVien/Areas/Admin/Controllers/AuthorController.cs
using DataProvider.Model;
using QuanLyThuVien.Service;
using System;
using System.Linq;
using System.Web.Mvc;

namespace QuanLyThuVien.Areas.Admin.Controllers
{
    public class AuthorController : BaseController
    {
        private IAuthorService _authorService;

        public AuthorController(IAuthorService authorService)
        {
            this._authorService = authorService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult List(int page = 1, string searchKey = "")
        {
            var result = _authorService.GetAllWithPageListSearch(page, 12, searchKey);
            return Json(new
            {
                data = result.Select(x => new
                {
                    AuthorID = x.AuthorID,
                    AuthorName = x.AuthorName,
                    DescriptionAuthor = x.DescriptionAuthor,
                    Alias = x.Alias
                }),
                pageNumber = result.PageCount,
                keyword = searchKey
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add(Author auth)
        {
            try
            {
                auth.Status = 1;
                _authorService.Create(auth);
                return Json(new { success = true, message = "Thêm thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetbyID(int ID)
        {
            var auth = _authorService.GetById(ID);
            return Json(new
            {
                AuthorID = auth.AuthorID,
                AuthorName = auth.AuthorName,
                DescriptionAuthor = auth.DescriptionAuthor,
                Alias = auth.Alias
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update(Author auth)
        {
            try
            {
                auth.Status = 1;
                _authorService.Update(auth);
                return Json(new { success = true, message = "Sửa thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Delete(int ID)
        {
            try
            {
                var auth = _authorService.GetById(ID);
                auth.Status = 0;
                _authorService.Update(auth);
                return Json(new { success = true, message = "Xoá thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Controllers/BookController.cs
using DataProvider.Model;
using QuanLyThuVien.Common;
using QuanLyThuVien.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace QuanLyThuVien.Areas.Admin.Controllers
{
    public class BookController : BaseController
    {
        private IBookService _bookService;
        private IBookCategoryService _bookCategoryService;
        private IAuthorService _authorService;
        private IEbookService _ebookService;
        private IUserService _userService;
        private ITypeEbookService _typeEbookService;

        public BookController(ITypeEbookService typeEbookService, IUserService userService, IAuthorService authorService, IBookCategoryService bookCategoryService, IBookService bookService, IEbookService ebookService)
        {
            this._authorService = authorService;
            this._bookCategoryService = bookCategoryService;
            this._bookService = bookService;
            this._ebookService = ebookService;
            this._userService = userService;
            this._typeEbookService = typeEbookService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult List(int page = 1, string searchKey = "")
        {
            var result = _bookService.GetAllWithPageListSearch(page, 12, searchKey);
            //Lỗi A circular reference was detected while serializing an object of type
            return Json(new
            {
                data = result.Select(x => new
                {
                    BookID = x.BookID,
                    BookName = x.BookName,
                    Description = x.Description,
                    Alias = x.Alias,
                    AuthorID = x.Author,
                    CategoryID = x.Category,
                    ViewCount = x.ViewCount,
                    MoreImages = x.MoreImages,
                    CreatedDate = x.CreatedDate,
                    CreatedBy = x.CreatedBy,
                    TopHot = x.TopHot
                }),
                pageNumber = result.PageCount,
                keyword = searchKey
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Add()
        {
            IEnumerable<Author> listAuthor = _authorService.GetAllAuthor();
            ViewData["AuthorList"] = new SelectList(listAuthor, "AuthorID", "AuthorName");

            IEnumerable<BookCategory> listCategory = _bookCategoryService.GetAllBookCategory();
            ViewBag.ListCategory = new SelectList(listCategory, "CategoryID", "CategoryName");

            ViewBag.Title = "Thêm mới sách";

            return View();
        }

        [HttpPost]
        public ActionResult Add(Book book)
        {
            book.CreatedDate = DateTime.Now;
            var logininfo = (LoginInfor)Session[Constants.USERSESSION];
            User user = _userService.GetById(Convert.ToInt32(logininfo.UserID));
            book.CreatedBy = user.Name;
            book.Status = 1;
            book.ViewCount = 0;
            _bookService.Create(book);
            TempData["testmsg"] = " Thêm thành công ";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                int idnew = (id ?? 1);
                var model = _bookService.GetById(idnew);
                IEnumerable<Author> listAuthor = _authorService.GetAllAuthor();
                ViewBag.AuthorList = new SelectList(listAuthor, "AuthorID", "AuthorName");

                IEnumerable<BookCategory> listCategory = _bookCategoryService.GetAllBookCategory();
                ViewBag.ListCategory = new SelectList(listCategory, "CategoryID", "CategoryName");
                ViewBag.Title = "Chỉnh sửa";
                return View("Edit", model);
            }
            else
            {
                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                var bookOld = _bookService.GetById(book.BookID); bookOld.BookName = book.BookName; bookOld.Description = book.Description; bookOld.Alias = book.Alias; bookOld.AuthorID = book.AuthorID; bookOld.CategoryID = book.CategoryID; bookOld.MoreImages = book.MoreImages; bookOld.TopHot = book.TopHot;
                _bookService.Update(bookOld);
                RedirectToAction("Index");
            }
            return View("Index");
        }

        [HttpPost]
        public JsonResult Delete(int ID)
        {
            try
            {
                var book = _bookService.GetById(ID); book.Status = 0;
                _bookService.Update(book);
                return Json(new { success = true, message = "Xoá thành công" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAuthor()
        {
            var listAuthor = _authorService.GetAllAuthor().Select(x => new
            {
                authorID = x.AuthorID,
                authorName = x.AuthorName
            });
            return Json(listAuthor, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCategory()
        {
            var listCategory = _bookCategoryService.GetAllBookCategory().Select(x => new
            {
                CategoryID = x.CategoryID,
                CategoryName = x.CategoryName
            });
            return Json(listCategory, JsonRequestBehavior.AllowGet);
        }

        //Lấy danh sách chapter theo ID
        public ActionResult GetAllChapterByID(int page, int id)
        {
            var listChapter = _bookService.GetAllChapterByIDBook(page, 5, id);
            int pageNumber1 = listChapter.PageCount;
            int amounChapter1 = listChapter.Count;
            return Json(new
            {
                data = listChapter.Select(x => new
                {
                    ID = x.ChapterID,
                    NameChapter = x.NameChapter
                }),
                pageNumber = listChapter.PageCount,
                idbook = id,
                amountChapter = listChapter.Count
            }, JsonRequestBehavior.AllowGet);
        }

        //Lấy danh sách ebook theo ID
        public ActionResult GetAllEbookByIDBook(int page = 1, int idbook = 0)
        {
            var listEbook = _bookService.GetAllEbookByIDBook(page, 5, idbook);
            return Json(new
            {
                data = listEbook.Select(x => new
                {
                    BookID = idbook,
                    TypeEbookID = x.TypeEbookID,
                    TypeEbookName = x.NameType,
                    Link = x.Link
                }),
                pageNumber = listEbook.PageCount,
                idbook = idbook,
            }, JsonRequestBehavior.AllowGet);
        }

        //Lấy danh sách ebook hỗ trợ
        public ActionResult GetAllListTypeEbook()
        {
            var listTypeEbook = _typeEbookService.GetAllTypeEbook().Select(x => new
            {
                TypeEbookName = x.Name,
                TypeEbookID = x.TypeID
            });
            return Json(listTypeEbook, JsonRequestBehavior.AllowGet);
        }

        //Thêm mới một ebook
        public ActionResult AddEbook(Ebook ebookObj)
        {
            try
            {
                _ebookService.Create(ebookObj);
                return Json(new { success = true, message = "Thêm thành công", idbook = ebookObj.BookID }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Loại ebook này đã tồn tại. Vui lòng xoá hoặc thêm mới một loại ebook khác", idbook = ebookObj.BookID }, JsonRequestBehavior.AllowGet);
            }
        }

        //Update một ebook
        public JsonResult GetEbookByID(int idbook, int typeid)
        {
            var ebook = _ebookService.GetEbookByID2(idbook, typeid);
            return Json(new
            {
                BookID = idbook,
                TypeEbookID = typeid,
                LinkDownload = ebook.Link
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateEbook(Ebook ebookObj)
        {
            try
            {
                _ebookService.Update(ebookObj);
                return Json(new { success = true, message = "Sửa thành công", idbook = ebookObj.BookID }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.ToString(), idbook = ebookObj.BookID }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DeleteEbook(int idbook, int typeid)
        {
            try
            {
                var ebook = _ebookService.GetEbookByID2(idbook, typeid);
                _ebookService.Delete(ebook);
                return Json(new { success = true, message = "Xoá thành công", idbook = idbook }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.ToString(), idbook = idbook }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

QuanLyThuVien/QuanLyThuVien/Controllers/BookCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyThuVien.Controllers
{
    public class BookCategoryController : Controller
    {
        // GET: BookCategory
        public ActionResult Index()
        {
            return View();
        }
    }
}

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/Book/Add.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}

@section scripts{
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>*@
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="js/captcha/jquery.clientsidecaptcha.js" type="text/javascript"></script>
    <script src="/Areas/Admin/Scripts/Book.js"></script>
    <script>

        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    </script>

    <script>
    $("#btnReloadAuthor").on('click', function (e) {
        var url = '@Url.Action("GetAuthor", "Book")'; // Don't hard code your url's!
        var authornames = $('#ddlAuthor'); // cache it
        e.preventDefault(); e.preventDefault();
        $.getJSON(url, function (response) {
            authornames.empty(); // remove any existing options
            $.each(response, function (index, item) { // item is now an object containing properties ID and Text
                authornames.append($('<option></option>').text(item.authorName).val(item.authorID));
            });
        });
    });
    </script>

    <script>

    $("#btnReloadCategory").on('click', function (e) {
        var url = '@Url.Action("GetCategory", "Book")'; // Don't hard code your url's!
        var categorynames = $('#ddlCategory'); // cache it
        e.preventDefault(); e.preventDefault();
        $.getJSON(url, function (response) {
            categorynames.empty(); // remove any existing options
            $.each(response, function (index, item) { // item is now an object containing properties ID and Text
                categorynames.append($('<option></option>').text(item.CategoryName).val(item.CategoryID));
            });
        });
    });
    </script>

}

@Html.Partial("partial_form_edit_book")

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/Book/Edit.cshtml
@model DataProvider.Model.Book
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}
@section scripts{
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>*@
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    @*<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>*@
    <script src="js/captcha/jquery.clientsidecaptcha.js" type="text/javascript"></script>
    <script src="~/Areas/Admin/Scripts/notify.min.js"></script>
    <script src="/Areas/Admin/Scripts/Book.js"></script>

    <script>
        $(document).ready(function () {
            loadListChapterByID(@Model.BookID,1);
            loadListEbookByBook(@Model.BookID,1);
            getListTypeEbook();
        });
    </script>

    <script>

        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    </script>

    <script>
    $("#btnReloadAuthor").on('click', function (e) {
        var url = '@Url.Action("GetAuthor", "Book")'; // Don't hard code your url's!
        var authornames = $('#ddlAuthor'); // cache it
        e.preventDefault(); e.preventDefault();
        $.getJSON(url, function (response) {
            authornames.empty(); // remove any existing options
            $.each(response, function (index, item) { // item is now an object containing properties ID and Text
                authornames.append($('<option></option>').text(item.AuthorName).val(item.AuthorID));
            });
        });
    });
    </script>

    <script>

    $("#btnReloadCategory").on('click', function (e) {
        var url = '@Url.Action("GetCategory", "Book")'; // Don't hard code your url's!
        var categorynames = $('#ddlCategory'); // cache it
        e.preventDefault(); e.preventDefault();
        $.getJSON(url, function (response) {
            categorynames.empty(); // remove any existing options
            $.each(response, function (index, item) { // item is now an object containing properties ID and Text
                categorynames.append($('<option></option>').text(item.CategoryName).val(item.CategoryID));
            });
        });
    });
    </script>

}

<div class="row">
    @Html.Partial("partial_form_edit_book", Model)
    @Html.Partial("partial_Chapter", Model)
    @Html.Partial("partial_Ebook", Model)
</div>

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/Book/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin2.cshtml";
}

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Areas/Admin/Scripts/notify.min.js"></script>
    <script src="~/Areas/Admin/Scripts/Book.js"></script>
    @if (TempData["msgthongbao"] != null)
    {
        <script type="text/javascript">
            $.notify("@TempData["msgthongbao"]", {
                globalPosition: "top center",
                className: "success"
            });
        </script>
    }
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Sách</h3>
                    </div>
                    <div class="box-body">
                        <div class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6">
                                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Add","Book")'">Thêm mới</button>
                                </div>
                                <div class="col-sm-6" style="text-align:right">
                                    <label>Search: <input type="text" class="form-control" id="inputKeyword" /></label>
                                    <button class="btn" onclick="SearchClick()">Tìm</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <br />
                                    <table id="#mytab" class="table table-hover dataTable table-bordered">
                                        <thead>
                                            <tr role="row">
                                                <th>
                                                    ID
                                                </th>
                                                <th>
                                                    Tên sách
                                                </th>
                                                <th>
                                                    Mô tả
                                                </th>
                                                <th>
                                                    Alias
                                                </th>
                                                <th>
                                                    Tác giả
                                                </th>
                                                <th>
                                                    Thể loại
                                                </th>
                                                <th>
                                                    Lượt xem
                                                </th>
                                                <th width="180px">
                                                    Hình ảnh
                                                </th>
                                                <th>
                                                    Ngày tạo
                                                </th>
                                                <th>
                                                    Tạo bởi
                                                </th>
                                                <th>
                                                    Top hot
                                                </th>
                                                <th width="150px">
                                                    Action
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody class="tbody"></tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row" style="text-align: right">
                                <div class="dataTables_paginate paging_simple_numbers" style="padding-right: 15px">
                                    <ul class="pagination" id="phantrang" style="margin-top: -10px;margin-bottom: 0px;"></ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/Book/partial_Ebook.cshtml
@model DataProvider.Model.Book
<div class="col-md-6">
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-md-9">
                    <h3 class="box-title" style="margin-top:8px">Ebook của sách</h3>
                </div>
                <div class="col-md-3" style="text-align:right">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAddOrEditEbook" onclick="clearModalEbook();">Thêm mới ebook</button>
                </div>
            </div>

        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <table id="#tablePhuLuc" class="table table-hover dataTable table-bordered">
                        <thead>
                            <tr role="row">
                                <th>
                                    ID
                                </th>
                                <th>
                                    Loại ebook
                                </th>
                                <th>
                                    Link
                                </th>
                                <th width="150px">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody class="tableEbook"></tbody>
                    </table>
                </div>
            </div>
            <div class="row" style="text-align: right">
                <div class="dataTables_paginate paging_simple_numbers" style="padding-right: 15px">
                    <ul class="pagination" id="phanTrangEbook" style="margin-top: -10px;margin-bottom: 0px;"></ul>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="modalAddOrEditEbook" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Ebook</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <input type="hidden" id="bookID" value="@Model.BookID" />
                        @*<label for="TypeEbook">Thể loại ebook</label>*@
                        @*<a href='@Url.Action("Index","BookCategory")' id="btnNewCategory" class="btn btn-default" style="margin-top: 10px">Thêm mới thể loại</a>\
                            <button type="button" class="btn btn-default" id="btnReloadCategory" style="margin-top: 10px">Reload</button>*@
                    </div>
                    <div class="form-group">
                        <label>Select</label>
                        <select class="form-control" id="ddlTypename"></select>
                    </div>
                    <div class="form-group">
                        <label for="linkdownload">Link download</label>
                        <input type="text" class="form-control" id="linkDownload" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAddEbook" onclick="return AddEbook();">Add</button>
                <button type="button" class="btn btn-primary" id="btnUpdateEbook" style="display:none;" onclick="UpdateEbook();">Update</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

QuanLyThuVien/QuanLyThuVien/Areas/Admin/Views/Book/partial_form_edit_book.cshtml
@model DataProvider.Model.Book



<div class="col-md-6">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">@ViewBag.Title</h3>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <form role="form">
                <div class="box-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label for="bookname">Tên sách</label>
                        @Html.HiddenFor(model => model.BookID)
                        @Html.TextBoxFor(model => model.BookName, new { @class = "form-control", placeholder = "Nhập tên sách" })
                    </div>
                    <div class="form-group">
                        <label>Mô tả</label>
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Nhập...", rows = "3" })
                    </div>
                    <div class="form-group">
                        <label for="alias">Alias</label>
                        @Html.TextBoxFor(model => model.Alias, new { @class = "form-control", placeholder = "Ví dụ: tony-buoi-sang" })
                    </div>
                    <div class="form-group">
                        <label>Tác giả</label>
                        @Html.DropDownListFor(model => model.AuthorID, (SelectList)ViewBag.AuthorList, "", new { @class = "form-control", @id = "ddlAuthor" })
                        <a href='@Url.Action("Index","Author")' id="btnNewAuthor" class="btn btn-default" target="_blank" style="margin-top: 10px">Thêm mới tác giả</a>
                        <button type="button" class="btn btn-default" id="btnReloadAuthor" style="margin-top: 10px">Reload</button>
                    </div>
                    <div class="form-group">
                        <label>Thể loại</label>
                        @Html.DropDownListFor(model => model.CategoryID, ViewBag.ListCategory as SelectList, "", new { @class = "form-control", @id = "ddlCategory" })
                        <a href='@Url.Action("Index","BookCategory")' id="btnNewCategory" class="btn btn-default" target="_blank" style="margin-top: 10px">Thêm mới thể loại</a>
                        <button type="button" class="btn btn-default" id="btnReloadCategory" style="margin-top: 10px">Reload</button>
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        @Html.TextBoxFor(model => model.MoreImages, new { @class = "form-control", @id = "txtImage" })
                        <button type="button" id="btnSelectImage" class="btn btn-default" style="margin-top: 10px">Chọn file</button>
                    </div>
                    <div class="checkbox">
                        <label>
                            @Html.EditorFor(model => model.TopHot) Top Hot
                        </label>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Index","Book")'">Trở về</button>
                </div>
            </form>
        }
    </div>
</div>